### ISSUE TITLE
Layout completely broken with devices with safe area

### ISSUE THREAD

**Issue by jasonnam** [canhth/SurveysChallenge#8]
![2019-04-17 09 44 56](https://user-images.githubusercontent.com/3154042/56257177-8ff59080-60f5-11e9-91f5-287755e7167f.gif)

**Comment by canhth** [comment]
Hi @jasonnam,

Thank you for your notice, This issue has been fixed by this PR: https://github.com/hoangcanhsek6/SurveysChallenge/pull/9.

Could you please help me to re-run the app and verify this issue again? 

Regards,
